"""Crypto trading automation primitives for TradingAgents.

This package is intentionally separate from the stock-oriented graph so crypto
venue adapters can mature behind their own risk gates before any live order
path is enabled.
"""

from .config import CryptoTradingConfig
from .autopilot import AutoPilotCycleResult, CryptoAutoPilot, CryptoAutoPilotSafetyError
from .adoption import (
    GITHUB_ADOPTION_SOURCES,
    SourceAdoption,
    adoption_by_key,
    adoption_keys,
    adoption_sources,
)
from .attention_harvester import AttentionHarvester, AttentionHarvestResult
from .backtest import (
    BacktestCandidateDecision,
    BacktestCandidateRules,
    BacktestInventoryBridgeConfig,
    BacktestInventoryEvent,
    BacktestReport,
    BacktestSweepCase,
    BacktestSweepReport,
    BacktestSweepResult,
    BacktestTrade,
    CryptoBacktester,
    CryptoBacktestSweepRunner,
)
from .binance_diagnostics import BinanceDiagnosticReport, BinanceDiagnostics
from .circuit_breaker import CircuitBreakerState, DailyLossCircuitBreaker
from .decision_journal import DecisionJournalWrite, write_workflow_report
from .engine import CryptoTradingEngine
from .evolution import (
    EvolutionArchiveStore,
    CryptoEvolutionRunner,
    CryptoGenomeEvaluator,
    EvolutionCandidate,
    EvolutionEnvironment,
    EvolutionGenerationStat,
    EvolutionLabPreset,
    EvolutionPopulationPlan,
    EvolutionPresetValidation,
    EvolutionPromotionResult,
    EvolutionRunReport,
    EvolutionRunStore,
    EvolutionWindowStat,
    FinalSampleReview,
    GenomeScore,
    InventoryBridgeStats,
    LunarGenome,
    MonteCarloReview,
    RuntimeChampionApplication,
    SeasonRegime,
    SeasonScore,
    evolution_html_output_path,
    evolution_archive_sections,
    evolution_champion_cache_path,
    evolution_compare_sections,
    evolution_output_paths,
    evolution_preset_sections,
    evolution_preset_template,
    evolution_record_sections,
    evolution_run_id,
    evolution_run_ledger_path,
    evolution_run_sections,
    evolution_runs_sections,
    ghost_dca_return_pct,
    load_archive_elite_genomes,
    load_archive_environment_anchor,
    load_runtime_champion_config,
    load_evolution_preset,
    monte_carlo_trade_review,
    render_evolution_preset_html,
    render_evolution_preset_markdown,
    render_evolution_archive_html,
    render_evolution_archive_markdown,
    render_evolution_compare_html,
    render_evolution_compare_markdown,
    render_evolution_record_html,
    render_evolution_record_markdown,
    render_evolution_runs_html,
    render_evolution_runs_markdown,
    render_evolution_run_html,
    render_evolution_run_markdown,
    score_backtest_report,
    validate_evolution_preset,
)
from .hyperliquid_client import (
    HyperliquidAPIError,
    HyperliquidBookLevel,
    HyperliquidClient,
    HyperliquidMarket,
    HyperliquidOrderBook,
)
from .hyperliquid_diagnostics import HyperliquidDiagnosticReport, HyperliquidDiagnostics
from .hyperliquid_execution import (
    HyperliquidExecutionAdapter,
    HyperliquidExecutionError,
    HyperliquidSignerStatus,
)
from .hyperliquid_stream import (
    HyperliquidEventArchive,
    HyperliquidStreamError,
    HyperliquidStreamEvent,
    HyperliquidStreamRunSummary,
    HyperliquidStreamService,
    HyperliquidStreamSubscription,
    default_stream_archive_path,
    stream_event_from_message,
)
from .live_readiness import (
    LiveReadinessChecker,
    LiveReadinessReport,
    ReadinessCheck,
    ReadinessTarget,
)
from .market_quality import MarketQualityDecision, MarketQualityGate
from .models import OpportunitySignal, OrderIntent, RiskDecision
from .order_recovery import OrderRecoveryResult, OrderRecoveryService
from .performance import PerformanceSummary, summarize_performance
from .paper_queue import (
    PaperQueueItem,
    PaperQueuePlan,
    build_paper_queue_plan,
    paper_queue_output_paths,
)
from .paper_status import PaperStatusSummary, PaperStreamEvidence, summarize_paper_status
from .position_guardian import PositionGuardian, PositionGuardDecision, PositionGuardResult
from .positions import PositionRecord, PositionStore
from .protective_orders import ProtectiveOrderPlan
from .regime import RegimeAssessment, RegimeEngine, RegimeSymbolSnapshot
from .strategy_fusion import HIGH_STAR_STRATEGY_REFERENCES, StrategyFusionEngine
from .stream_status import (
    GLOBAL_CHANNELS,
    REQUIRED_SYMBOL_CHANNELS,
    StreamFreshnessRow,
    StreamStatusSummary,
    summarize_stream_status,
)
from .workflow_report import CryptoTradingAgentsWorkflow, CryptoWorkflowReport

__all__ = [
    "CryptoTradingConfig",
    "CryptoTradingEngine",
    "CryptoTradingAgentsWorkflow",
    "CryptoWorkflowReport",
    "DecisionJournalWrite",
    "AutoPilotCycleResult",
    "GITHUB_ADOPTION_SOURCES",
    "AttentionHarvester",
    "AttentionHarvestResult",
    "BacktestCandidateDecision",
    "BacktestCandidateRules",
    "BacktestInventoryBridgeConfig",
    "BacktestInventoryEvent",
    "BacktestReport",
    "BacktestSweepCase",
    "BacktestSweepReport",
    "BacktestSweepResult",
    "BacktestTrade",
    "BinanceDiagnosticReport",
    "BinanceDiagnostics",
    "CircuitBreakerState",
    "CryptoAutoPilot",
    "CryptoBacktester",
    "CryptoBacktestSweepRunner",
    "CryptoAutoPilotSafetyError",
    "CryptoEvolutionRunner",
    "CryptoGenomeEvaluator",
    "GLOBAL_CHANNELS",
    "DailyLossCircuitBreaker",
    "EvolutionCandidate",
    "EvolutionEnvironment",
    "EvolutionGenerationStat",
    "EvolutionArchiveStore",
    "EvolutionLabPreset",
    "EvolutionPopulationPlan",
    "EvolutionPresetValidation",
    "EvolutionPromotionResult",
    "EvolutionRunReport",
    "EvolutionRunStore",
    "EvolutionWindowStat",
    "FinalSampleReview",
    "GenomeScore",
    "InventoryBridgeStats",
    "HIGH_STAR_STRATEGY_REFERENCES",
    "HyperliquidAPIError",
    "HyperliquidBookLevel",
    "HyperliquidClient",
    "HyperliquidDiagnosticReport",
    "HyperliquidDiagnostics",
    "HyperliquidExecutionAdapter",
    "HyperliquidExecutionError",
    "HyperliquidMarket",
    "HyperliquidOrderBook",
    "HyperliquidSignerStatus",
    "HyperliquidEventArchive",
    "HyperliquidStreamError",
    "HyperliquidStreamEvent",
    "HyperliquidStreamRunSummary",
    "HyperliquidStreamService",
    "HyperliquidStreamSubscription",
    "LiveReadinessChecker",
    "LiveReadinessReport",
    "MarketQualityDecision",
    "MarketQualityGate",
    "LunarGenome",
    "MonteCarloReview",
    "OpportunitySignal",
    "OrderIntent",
    "OrderRecoveryResult",
    "OrderRecoveryService",
    "PaperQueueItem",
    "PaperQueuePlan",
    "PaperStatusSummary",
    "PaperStreamEvidence",
    "PerformanceSummary",
    "PositionGuardian",
    "PositionGuardDecision",
    "PositionGuardResult",
    "PositionRecord",
    "PositionStore",
    "ProtectiveOrderPlan",
    "ReadinessCheck",
    "ReadinessTarget",
    "REQUIRED_SYMBOL_CHANNELS",
    "RiskDecision",
    "RegimeAssessment",
    "RegimeEngine",
    "RegimeSymbolSnapshot",
    "RuntimeChampionApplication",
    "SeasonRegime",
    "SeasonScore",
    "SourceAdoption",
    "StreamFreshnessRow",
    "StreamStatusSummary",
    "StrategyFusionEngine",
    "adoption_by_key",
    "adoption_keys",
    "adoption_sources",
    "build_paper_queue_plan",
    "default_stream_archive_path",
    "evolution_html_output_path",
    "evolution_archive_sections",
    "evolution_champion_cache_path",
    "evolution_compare_sections",
    "evolution_output_paths",
    "evolution_preset_sections",
    "evolution_preset_template",
    "evolution_record_sections",
    "evolution_run_id",
    "evolution_run_ledger_path",
    "evolution_run_sections",
    "evolution_runs_sections",
    "ghost_dca_return_pct",
    "load_archive_elite_genomes",
    "load_archive_environment_anchor",
    "load_runtime_champion_config",
    "load_evolution_preset",
    "monte_carlo_trade_review",
    "paper_queue_output_paths",
    "render_evolution_preset_html",
    "render_evolution_preset_markdown",
    "render_evolution_archive_html",
    "render_evolution_archive_markdown",
    "render_evolution_compare_html",
    "render_evolution_compare_markdown",
    "render_evolution_record_html",
    "render_evolution_record_markdown",
    "render_evolution_runs_html",
    "render_evolution_runs_markdown",
    "render_evolution_run_html",
    "render_evolution_run_markdown",
    "score_backtest_report",
    "stream_event_from_message",
    "summarize_stream_status",
    "summarize_paper_status",
    "summarize_performance",
    "validate_evolution_preset",
    "write_workflow_report",
]
