param(
    [switch]$LiveApi
)

$env:TRADINGAGENTS_CRYPTO_EXCHANGE_PROVIDER = "okx"
$env:TRADINGAGENTS_CRYPTO_OKX_DEMO = if ($LiveApi) { "false" } else { "true" }
$env:TRADINGAGENTS_CRYPTO_OKX_INST_TYPE = "SWAP"
$env:TRADINGAGENTS_CRYPTO_OKX_QUOTE_CCY = "USDT"
$env:TRADINGAGENTS_CRYPTO_OKX_MAX_LEVERAGE = "1"
$env:TRADINGAGENTS_CRYPTO_OKX_DEMO_EXECUTION_ENABLED = "false"
$env:TRADINGAGENTS_CRYPTO_OKX_TD_MODE = "cross"
$env:TRADINGAGENTS_CRYPTO_OKX_REQUIRE_NET_MODE = "true"
$env:TRADINGAGENTS_CRYPTO_OKX_REQUIRE_PROTECTIVE_ORDERS = "true"
$env:TRADINGAGENTS_CRYPTO_OKX_WS_PUBLIC_URL = ""
$env:TRADINGAGENTS_CRYPTO_OKX_WS_BUSINESS_URL = ""
$env:TRADINGAGENTS_CRYPTO_SYMBOLS = "BTC,ETH,SOL,XRP"
$env:TRADINGAGENTS_CRYPTO_INTERVAL = "15m"
$env:TRADINGAGENTS_CRYPTO_EXECUTION_MODE = "analysis"
$env:TRADINGAGENTS_CRYPTO_ENABLE_LIVE_ORDERS = "false"
$env:TRADINGAGENTS_CRYPTO_LIVE_CONFIRM_PHRASE = "I_UNDERSTAND_THIS_PLACES_REAL_OKX_ORDERS"
$env:TRADINGAGENTS_CRYPTO_PROTECTIVE_OCO_ENABLED = "true"
$env:TRADINGAGENTS_CRYPTO_MARKET_QUALITY_ENABLED = "true"
$env:TRADINGAGENTS_CRYPTO_MARKET_QUALITY_MIN_OPEN_INTEREST_USD = "1000000"

$stateDir = Join-Path $HOME ".tradingagents\crypto"
$env:TRADINGAGENTS_CRYPTO_STATE_DIR = $stateDir
$env:TRADINGAGENTS_CRYPTO_EMERGENCY_STOP_FILE = Join-Path $stateDir "EMERGENCY_STOP"

Write-Host "OKX environment loaded."
Write-Host "Provider: $env:TRADINGAGENTS_CRYPTO_EXCHANGE_PROVIDER"
Write-Host "OKX demo: $env:TRADINGAGENTS_CRYPTO_OKX_DEMO"
Write-Host "Execution mode: $env:TRADINGAGENTS_CRYPTO_EXECUTION_MODE"
Write-Host "Demo execution: $env:TRADINGAGENTS_CRYPTO_OKX_DEMO_EXECUTION_ENABLED"
Write-Host "Live orders: $env:TRADINGAGENTS_CRYPTO_ENABLE_LIVE_ORDERS"
Write-Host "State dir: $env:TRADINGAGENTS_CRYPTO_STATE_DIR"
